### ISSUE TITLE
need bar & spinner to be different colors

### ISSUE THREAD

**Issue by joenorton** [rstacruz/nprogress#121]
It looks like we set the nprogress-color var and then that is used to define the other colors; my problem is I want my bar to be white, but my spinner non-white (like.. gray?).

Could this be split to nprogress-bar-color & nprogress-spinner-color? They could all be set to the default same nprogress-color but with ability to redefine?

Am I missing a simpler way to do this?

Thanks for looking into this. If I have a chance maybe I can put together a PR for it.

**Comment by joenorton** [comment]
Just realized you don't have .less files up here? what gives? I want to make a commit to the less version of this. It's small, and accomplishes what I mentioned above.

**Comment by rstacruz** [comment]
you can do this with some CSS, something like:

```
#nprogress .bar {
  background: blue;
}

#nprogress .spinner-icon {
  border-top-color: red;
  border-left-color: red;
}
```

**Comment by joenorton** [comment]
You are right. That's easier. Thanks, keep up the good work!
