### ISSUE TITLE
Create a counter of how many times start() was executed

### ISSUE THREAD

**Issue by jeerbl** [rstacruz/nprogress#130]
I think having a counter of how many times the start method has been called could be cool.

Therefore, if you have 2 ajax calls at the same time, you could now call done() when both of them are finished.

**Comment by createvibe** [comment]
+1

I had to wrap this in a service.  And I had to play with the animation timeout to make it more smooth.

https://gist.github.com/createvibe/60f454bcf0266247010a

**Comment by jbrunel** [comment]
Done in https://github.com/rstacruz/nprogress/pull/132
