### ISSUE TITLE
Progress bar still visible after 'done' in Firefox

### ISSUE THREAD

**Issue by Aleksandr-ru** [rstacruz/nprogress#153]
The bug (or maybe a bug of mozilla) can be reproduced in Firefox 48.0 under Ubuntu Linux (Elementary OS Freya):
1. Open the page http://ricostacruz.com/nprogress/
2. Press the " NProgress.start()" button
3. Press the "NProgress.done()" button
4. See the bar still partially visible at top
If you switch to another tab and then switch back everything become ok (no bar visible).
What is it? Bug of nprogress or browser?

**Comment by Kepro** [comment]
@Aleksandr-ru i open in in firefox, this demo http://ricostacruz.com/nprogress/ and it's working

**Comment by Aleksandr-ru** [comment]
In Firefox 49 the bug seems to be absent. So it looks like a bug of browser not nprogress.
