### ISSUE TITLE
[Question] axious support

### ISSUE THREAD

**Issue by the94air** [rstacruz/nprogress#193]
How to integrate the progress with axios library (restart with any ajax request)?

**Comment by s00d** [comment]
```js
import NProgress from 'nprogress';
NProgress.configure({
    easing: 'linear',
    speed: 350
});
Axios.defaults.transformRequest.push(function (data, headers) {
    NProgress.start();
    return data;
})

Axios.defaults.transformResponse.push(function (data, headers) {
    NProgress.done();
    return data;
})
```

**Comment by the94air** [comment]
Awesome.[Pace progress](https://github.com/HubSpot/pace) is not maintained any more And nprogress is a perfect replacement. Thanks @s00d
https://jsfiddle.net/the94air/bpzyyay9/

**Comment by RamyRais** [comment]
@the94air since the isssue is resolved could you close it?

**Comment by the94air** [comment]
Oops, forgot  about that.
