### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by DanielRuf** [rstacruz/nprogress#200]
It seems the last actual code changes were some years ago and Travis CI is not setup.

Is anyone still maintaining it?

**Comment by RamyRais** [comment]
i am trying to maintain it here https://github.com/RamyRais/multi-nprogress

**Comment by DanielRuf** [comment]
> i am trying to maintain it here RamyRais/multi-nprogress

Sounds good. Are you open for new maintainers and are there plans to move this to an org account?

**Comment by RamyRais** [comment]
yes your are free to join. Currently i don't have any plan or any organisation account. I am just willing to solve issue found by others.

**Comment by hozefaj** [comment]
@RamyRais Is the library published npm under a new name?

**Comment by RamyRais** [comment]
@hozefaj yes it is, this is the [link](https://www.npmjs.com/package/multi-nprogress).
if you find issues or you want to solve some with a pull request, feel free.

**Comment by dandrei** [comment]
@RamyRais if it's being maintained, why not make it into a standalone project, with its own branding `README.md` and everything?

**Comment by anselal** [comment]
The project is still active, check out https://github.com/rstacruz/nprogress/pull/218
