### ISSUE TITLE
Build in imageLoaded.js

### ISSUE THREAD

**Issue by liammday** [rstacruz/nprogress#203]
I've found it useful to incorporate [imageLoaded.js](https://imagesloaded.desandro.com) to the `NProgress.done();` function. Could this be built in to the core script rather than the end user having to combine the 2 scripts?

**Comment by hubseven** [comment]
@liammday try this

``
NProgress.start();
$(document).ready(function() {

    $('body')
        .imagesLoaded({ background: true })
        .always(function() { NProgress.done(); })
        .progress(function() { NProgress.inc(); });

        $('#container')
            .imagesLoaded({ background: true })
            .progress(function() { NProgress.inc(); })
            .always(function() {
                NProgress.done();
            });

});
