### ISSUE TITLE
Actual loading progression with pjax ?

### ISSUE THREAD

**Issue by ghost** [rstacruz/nprogress#22]
I'm sorry if it has been answered elsewhere, but I only found documentation with turbolinks, but not pjax. How can I configure nprogress so it displays the "true" loading % progress of pjax requests ?

Thanks a lot !

This is my code :

$(document).pjax('a', '#pjax-container');
$(document).on('pjax:send', function() { NProgress.start(); })
$(document).on('pjax:complete', function() { NProgress.done(); })
$(document).on('pjax:timeout', function(event) { event.preventDefault(); })

From what I get it "simulates" loading, but not the actual progression. Is such a thing even possible ?

**Comment by hynese** [comment]
@nzwsch Lovely! Thank you.

**Comment by rstacruz** [comment]
seems like a reasonable addition to the readme.

**Comment by caarlos0** [comment]
@rstacruz or maybe just reference nprogress-rails, which already support turbolinks...

**Comment by eberkund** [comment]
Is there a way to make it so that the loading bar is not displayed when a user presses the back button?

**Comment by vipersec** [comment]
I agree with @eberkund I would also like to find that out.

**Comment by kwentworth** [comment]
You can use pjax:send instead of pjax:start

**Comment by zmzxx** [comment]
的存储形式

**Comment by xbgyh** [comment]
fdffdsfds

**Comment by anildalar** [comment]
Excellent Library
