### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by kenkage** [rstacruz/nprogress#225]
I'm using this in angular 8 app.
There's a export written **"export default NProgress;"** in nprogress.js at path **"node_modules\nprogress\src"** which gives error on console **"Uncaught SyntaxError: Unexpected token 'export'"**.

**Comment by khaledalam** [comment]
`edgardmessias/yii2-nprogress` package start using `bower-asset/nprogress` version `1.0.0-1` which has different structure and uses export keyword in `nprogress.js` file.

Use bower-asset/nprogress version 0.2.0 instead of "*" or 1.0.0-1 or higher
