### ISSUE TITLE
Is this project under any sort of maintenance?

### ISSUE THREAD

**Issue by phpb-com** [rstacruz/nprogress#242]
If this is a dead project, are there any alternatives that have similar API and are maintained?

**Comment by zeozeozeo** [comment]
what's the problem with it not being maintained?

**Comment by danielbarion** [comment]
@phpb-com I use that one https://www.npmjs.com/package/@tanem/react-nprogress

also @rstacruz, can I suggest you create an organization to nprogress and add maintainers?
Like https://github.com/ReactTooltip/react-tooltip
