### ISSUE TITLE
progress visible when browser's back button used

### ISSUE THREAD

**Issue by slbug** [rstacruz/nprogress#8]
Steps to reproduce:
1. Click any link with enabled turbolinks. Progress will appear and dissapear when page content loaded
2. Press back button in browser and you will see progress bar with spinner forever.

**Comment by ctf0** [comment]
for the new v5 the method will be
```js
.on('turbolinks:click', function() {
	NProgress.start();
})
.on('turbolinks:render', function() {
	NProgress.done(); // to work with the above method on first visit
	NProgress.remove(); // to work on back btn click, restore event
});

**Comment by rstacruz** [comment]
Thanks! I've updated the turbolinks instructions.

https://github.com/rstacruz/nprogress/blob/master/Readme.md#turbolinks-version-5

**Comment by mrkongo** [comment]
Dear @ctf0, is this necessary? Without that code I can use very good nprogress. Why?

**Comment by ctf0** [comment]
@mrkongo u dont need to use the code if it serves no purpose to u, basicly its a solution for the main issue "having nprogress visible on going back"

**Comment by ctf0** [comment]
@rstacruz after more testing its recommended to use TL default progress instead of nprogress as its inaccurate , actually even TL progress is not perfect but the margin of false progress is smaller than nprogress.

**Comment by Semaerdem3536** [comment]
NProgress.start()
