### ISSUE TITLE
Multitasking using jquery ajax

### ISSUE THREAD

**Issue by blpraveen** [rstacruz/nprogress#91]
I am working on a application which sends multiple Jquery ajax request on the search landing page. Ajax request is send to different api's to get the search result data. Can i have one nprogress loader to all the ajax request. which closes on the all the ajax is completed

**Comment by Devian50** [comment]
I think creating your own function to handle that would be easier.
```javascript
var numAjaxRequests = 0;
function numRequests(addRequest){
    if(typeof addRequest==='number'){
        numAjaxRequests = addRequest;
        NProgress.start();
    } else {
        if(addRequest){
            NProgress.start();
            numAjaxRequests++;
        } else {
            numAjaxRequests--;
            if(numAjaxRequests<=0){
                NProgress.done();
                numAjaxRequests = 0;
            }
        }
    }
}
```

`addRequest` is a boolean `true` or `false`. When you start an Ajax request you want to be part of the "group" call `numRequests(true);` and when one of those requests finish, have it call `numRequests(false);` Once you've called `numRequests(false)` the same amount of times you called `numRequests(true);`, `NProgress.done();` will be called completing the progress bar.

Alternatively, you can supply a number into `numRequests()` which would be the same as calling `numRequests(true)` that number of times.

This also allows you to have other Ajax functions running that won't interfere with the progress bar.

Seeing as this is a year late, you've probably solved this but I'll post it anyways for people like me who come across it.

**Comment by Svish** [comment]
Might be missing something, but why not just use the `ajaxStart` and `ajaxStop` events? This will make the progress appear when any ajax request starts, and go away once all have completed.

```
$(function()
{
	$(document)
		.ajaxStart(NProgress.start)
		.ajaxStop(NProgress.done);
});
```

**Comment by rstacruz** [comment]
@Svish, that's pretty neat.

**Comment by ArmorDarks** [comment]
@Svish Thanks for sharing, but your example won't work when you have few simultaneous ajax requests. One of them will finish earlier and remove bar completely due to fired `NProgress.done()`, while in fact there is still another ajax request in progress.

**Comment by Svish** [comment]
@ArmorDarks Hm... in that case I think you might be using the wrong event? The `ajaxStop` event shouldn't be fired until *all* active ajax requests have completed. I.e. as long as at least one request is still running, the bar should not be removed.
