### ISSUE TITLE
[EXPIRED] Uncaught ReferenceError: NProgress is not defined

### ISSUE THREAD

**Issue by sergeevabc** [rstacruz/nprogress#98]
Consider rethinking how nProgress is implemented as it throws error if loaded near `</body>`.
For example, you could put [any of these functions](https://gist.github.com/sergeevabc/246dff8b8d3d6f106c38) into the end of file, still they will work.

**Comment by Xuyingying1119** [comment]
Uncaught ReferenceError: NProgress is not defined
